version: "3"
services:
  mysql:
    build:
      context: ./docker/mysql
      args:
        mysql_version: ${MYSQL_VERSION}
    container_name: ${DOCKER_PROJECT_NAME}-mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:3306
    restart: always

  pma:
    build:
      context: ./
      dockerfile: ./docker/pma/Dockerfile
    container_name: ${DOCKER_PROJECT_NAME}-pma
    ports:
      - ${WEB_PORT}:80
    restart: always
